# Generated by Django 5.2.2 on 2025-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0002_remove_rifa_numero_final_remove_rifa_numero_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
