# Generated by Django 5.2.2 on 2025-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='numero_final',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='numero_inicial',
        ),
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='fecha_sorteo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='precio_numero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='numero',
            unique_together={('rifa', 'numero')},
        ),
    ]
