# Generated by Django 5.2.2 on 2025-06-17 00:35

import app_rifas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='numero_final',
            field=models.PositiveIntegerField(default=199999),
        ),
        migrations.AddField(
            model_name='rifa',
            name='numero_inicial',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, validators=[app_rifas.models.validar_cedula_ecuador]),
        ),
    ]
