# Generated by Django 5.2.2 on 2025-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje principal')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje del Sorteo',
                'verbose_name_plural': 'Mensaje del Sorteo',
            },
        ),
    ]
