# Generated by Django 5.2.2 on 2025-06-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0002_rifa_numero_final_rifa_numero_inicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroBendecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, unique=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bendecidos', to='app_rifas.rifa')),
            ],
        ),
    ]
