# Generated by Django 5.2.2 on 2025-06-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0003_numerobendecido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumeroFavoritoVendido',
        ),
        migrations.AlterField(
            model_name='numeroseleccionado',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='numero_final',
            field=models.PositiveIntegerField(default=19999),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='numero_inicial',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
