# Generated by Django 5.2.2 on 2025-06-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0004_delete_numerofavoritovendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerobendecido',
            name='numero',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
