# Generated by Django 5.2.2 on 2025-06-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rifas', '0005_alter_numerobendecido_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('paypal', 'PayPal')], max_length=50),
        ),
    ]
