"""
Django settings for proyecto_chavez project.

Generated by 'django-admin startproject' using Django 5.2.2.
"""

import os
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4g39hcw295c@%$h_n75%(tpgkln72b_88iy&k%(qa56r#yd85c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['f234-27-50-12-226.ngrok-free.app', 'localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'app_rifas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_chavez.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'app_rifas/templates'),  # vistas personalizadas de tu app
            os.path.join(BASE_DIR, 'templates'),            # templates globales como admin/recaudacion_total.html
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_chavez.wsgi.application'

# Base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internacionalización
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# PayPal Sandbox Credentials
PAYPAL_CLIENT_ID = 'AS09xmbV5tXfYZCD60ZKWVTwSAXOtAiaiv5Oz1qgeiV9qIdLkvUov-9iC3nvdwIk3L3mC18ShVuUuqzy'
PAYPAL_CLIENT_SECRET = 'EJUqdRWgwSGx1qD7hvyA2cSsQdvglCK7ARdbU8hnIbMfTRZqwk9-aq1yjolH_TI7wcd0ld4g3A4TT9A0'
PAYPAL_API_BASE = 'https://api.sandbox.paypal.com'  # usar sandbox en pruebas

# Archivos estáticos
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Archivos multimedia (para imágenes y subidas)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL base del sitio (para generación de enlaces absolutos o QR)
SITE_URL = "http://127.0.0.1:8000"

PAYPAL_API_BASE = "https://api.sandbox.paypal.com"
